config/routes.rb
Rails.application.routes.draw do
  devise_for :administrators
  devise_for :fellows
  resources :welcome
  root 'welcome#index'
  #Botones de la pagina, para controladores 
  get 'quienessomos'  => 'nosotros#quienessomos'
  get 'administrador'  => 'administrador#administrador'
  get 'contacto'  => 'contacto#contacto'
  get 'servicio'  => 'servicios#servicio'
  resources :pipas
  resources :fellows
end

app/models/administrator.rb
class Administrator < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fellow.rb
class Fellow < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

    has_many :hours
end

app/models/pipa.rb
class Pipa < ApplicationRecord
end

app/controllers/administrador_controller.rb
class AdministradorController < ApplicationController
    before_action :authenticate_administrator!
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    #before_action :authenticate_fellow!

  #  layout :layout_by_resource

   # private
    #def layout_by_resource
     #   if devise_controller?
      #      "devise"
       # else 
        #    "application"
        #end
   # end 
   
end

app/controllers/contacto_controller.rb
class ContactoController < ApplicationController
end

app/controllers/fellows_controller.rb
class FellowsController < ApplicationController
    def index
        @fellows = Fellow.all
    end 

    def show
        @fellow = Fellow.find(params[:id])
    end 

    def edit
        @fellow = Fellow.find(params[:id])
    end 
    
    def update
        @fellow = Fellow.find(params[:id])
        if @fellow.update(fellow_params)
            redirect_to fellows_path
        else 
            render :edit
        end
    end 

    def destroy 
        @fellow = Fellow.find(params[:id])
        @fellow.destroy
        redirect_to fellows_path
    end 
    
    private 
    def fellow_params
        params.require(:fellow).permit(:nombre, :email, :cedula)
    end
end

app/controllers/nosotros_controller.rb
class NosotrosController < ApplicationController
    
end

app/controllers/perfil_controller.rb
class PerfilController < ApplicationController
    before_action :authenticate_fellow!
end

app/controllers/pipas_controller.rb
class PipasController < ApplicationController
    def index
        @pipas = Pipa.all
    end 
    def show
        @pipas = Pipa.sum(:numero)
    end 
end

app/controllers/servicios_controller.rb
class ServiciosController < ApplicationController
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/administrador_helper.rb
module AdministradorHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacto_helper.rb
module ContactoHelper
end

app/helpers/fellows_helper.rb
module FellowsHelper
end

app/helpers/nosotros_helper.rb
module NosotrosHelper
end

app/helpers/osos_helper.rb
module OsosHelper
    def gravatar_for(oso)
        gravatar_id = Digest::MD5::hexdigest(oso.email.downcase)
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
        image_tag(gravatar_url, alt: oso.name, class: "gravatar")
    end
    
end

app/helpers/perfil_helper.rb
module PerfilHelper
end

app/helpers/pipas_helper.rb
module PipasHelper
end

app/helpers/servicios_helper.rb
module ServiciosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
    def full_title(page_title = '')
        base_title = "HL Construccion"
        if page_title.empty?
          base_title
        else
          page_title + " | " + base_title
        end
      
    end
end

app/views/fellows/edit.html.erb
<%= form_for @fellow do |f| %>
    <div>
        <%= f.label :nombre %>
        <%= f.text_field :nombre %>
    </div>
    
    <div>
        <%= f.label :email %>
        <%= f.text_field :email %>
    </div>

    <div>
        <%= f.label :cedula %>
        <%= f.number_field :cedula %>
    </div>

    <div>
        <%= f.submit %>
    </div>
<% end %>

app/views/fellows/index.html.erb
<h1>Miembros</h1>
<table border="1" >
<tr>
<thead>
<th>Nombre</th>
<th>Email</th>
<th>Cedula</th>
<th>Modificar</th>
</thead>
</tr>
<% @fellows.each do |fellow|%>
    <tr>
    <td><%= fellow.nombre %></td>
    <td><%= link_to fellow.email, fellow_path(fellow) %></td>
    <td><%= fellow.cedula %></td>
    <td><%= link_to "Editar", edit_fellow_path(fellow) %></td>
    <td><%= link_to "Eliminar", fellow, method: :delete, data: {confirm: "¿Desea eliminar los datos de esta persona?"} %></td>
    </tr>
<% end %>

</table>

app/views/fellows/show.html.erb
<h1><%= @fellow.email %></h1>

app/views/pipas/index.html.erb
<h1> perrras </h1>
<ul>
<% @pipas.each do |pipa| %>
    <li><h4>nombre:<%= pipa.nombre %></h> </li>
    <li><h4>numero:<%= pipa.numero %></h> </li>
    <li><h4>Pepe:<%= pipa.pepe %></h> </li>
    <% end %>
</ul>

app/views/pipas/show.html.erb
    <h1><%= @pipas %></h1>