config/routes.rb
Rails.application.routes.draw do
  devise_for :administrators
  devise_for :fellows
  resources :welcome
  root 'welcome#index'
  #Botones de la pagina, para controladores 
  get 'quienessomos'  => 'nosotros#quienessomos'
  get 'administrador'  => 'administrador#administrador'
  get 'contacto'  => 'contacto#contacto'
  get 'servicio'  => 'servicios#servicio'
  resources :pipas
  resources :fellows
end

app/models/administrator.rb
class Administrator < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fellow.rb
class Fellow < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

    has_many :hours
end

app/models/pipa.rb
class Pipa < ApplicationRecord
end

app/controllers/contacto_controller.rb
class ContactoController < ApplicationController
end

app/controllers/fellows_controller.rb
class FellowsController < ApplicationController
    def index
        @fellows = Fellow.all
    end 

    def show
        @fellow = Fellow.find(params[:id])
    end 

    def edit
        @fellow = Fellow.find(params[:id])
    end 
    
    def update
        @fellow = Fellow.find(params[:id])
        if @fellow.update(fellow_params)
            redirect_to fellows_path
        else 
            render :edit
        end
    end 

    def destroy 
        @fellow = Fellow.find(params[:id])
        @fellow.destroy
        redirect_to fellows_path
    end 
    
    private 
    def fellow_params
        params.require(:fellow).permit(:nombre, :email, :cedula)
    end
end

app/controllers/nosotros_controller.rb
class NosotrosController < ApplicationController
    
end

app/controllers/perfil_controller.rb
class PerfilController < ApplicationController
    before_action :authenticate_fellow!
end

app/controllers/pipas_controller.rb
class PipasController < ApplicationController
    def index
        @pipas = Pipa.all
    end 
    def show
        @pipas = Pipa.sum(:numero)
    end 
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/administrador_helper.rb
module AdministradorHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacto_helper.rb
module ContactoHelper
end

app/helpers/fellows_helper.rb
module FellowsHelper
end

app/helpers/nosotros_helper.rb
module NosotrosHelper
end

app/helpers/osos_helper.rb
module OsosHelper
    def gravatar_for(oso)
        gravatar_id = Digest::MD5::hexdigest(oso.email.downcase)
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
        image_tag(gravatar_url, alt: oso.name, class: "gravatar")
    end
    
end

app/helpers/perfil_helper.rb
module PerfilHelper
end

app/helpers/pipas_helper.rb
module PipasHelper
end

app/helpers/servicios_helper.rb
module ServiciosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
    def full_title(page_title = '')
        base_title = "HL Construccion"
        if page_title.empty?
          base_title
        else
          page_title + " | " + base_title
        end
      
    end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  
  <nav>
    <ul>
  
      <li><%= link_to "Contacto", contacto_path %></li>
      <li><%= link_to "Administrador", new_administrator_session_path  %></li> 
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar-fixed navbar-inverse">
  <div class="container">
    <%= link_to "HL Construcciones", root_path, id: "logo" %>
    <nav>
      <ul class="nav  navbar-nav navbar-right">
      
        <li><%= link_to "Inicio",    root_path %></li>
        <li><%= link_to "Nosotros",  quienessomos_path %></li>
        <li><%= link_to "Proyecctos", '#' %></li>
        <li><%= link_to "Servicios", servicio_path %></li>
       
       
      
        <%- if fellow_signed_in? %>
        <li><%= link_to "Mi Perfil", '#' %></li>
        <li><%= link_to "Salir", destroy_fellow_session_path, method: :delete %></li>
        <% else %>
        <li><%= link_to "Log in", new_fellow_session_path  %></li>  
        <% end %>
        <%- if administrator_signed_in? %>
        <li><%= link_to "Salir", destroy_administrator_session_path, method: :delete %></li>
        <li><%= link_to "Administrador", administrador_path %></li>
        
        <% end %>
      
        </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all','data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

    <body>
      <%= render 'layouts/header' %>
        <div class="container">
        <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% end %>
          <%= yield %>
          <%= render 'layouts/footer' %>
         
        </div>
        
        
    </body>
</html>